CREATE TABLE IF NOT EXISTS complaints (
  id VARCHAR(255) PRIMARY KEY,
  user_id VARCHAR(255) NOT NULL,
  vendor_id VARCHAR(255) NOT NULL,
  transaction_id VARCHAR(255) NOT NULL,
  type ENUM('kerusakan', 'pembatalan') NOT NULL,
  description TEXT,
  evidence_url TEXT,
  status ENUM('PENDING_ADMIN', 'FORWARDED_TO_VENDOR', 'REFUND_PROCESSED', 'RESOLVED') NOT NULL DEFAULT 'PENDING_ADMIN',
  admin_note TEXT,
  vendor_note TEXT,
  refund_amount DECIMAL(18,2) DEFAULT 0,
  refund_method VARCHAR(100),
  refund_reference VARCHAR(255),
  refund_proof_url TEXT,
  refund_paid_at DATETIME(3),
  admin_verified_at DATETIME(3),
  forwarded_at DATETIME(3),
  vendor_processed_at DATETIME(3),
  resolved_at DATETIME(3),
  created_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  CONSTRAINT fk_complaints_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_complaints_vendor FOREIGN KEY (vendor_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_complaints_transaction FOREIGN KEY (transaction_id) REFERENCES transactions(id) ON DELETE CASCADE,
  INDEX idx_complaints_user_id (user_id),
  INDEX idx_complaints_vendor_id (vendor_id),
  INDEX idx_complaints_transaction_id (transaction_id),
  INDEX idx_complaints_status (status),
  INDEX idx_complaints_type (type),
  INDEX idx_complaints_created_at (created_at)
);
